server:
  port: 8080
  servlet:
    context-path: /
    application-display-name: ${spring.application.name}
  tomcat:
    accesslog:
      enabled: false

spring:
  application:
    name: sdc-operations-server
  profiles:
    active: dev
  messages:
    basename: messages
    encoding: UTF-8
    fallback-to-system-locale: false
    use-code-as-default-message: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
    serialization:
      INDENT_OUTPUT: true
      FAIL_ON_EMPTY_BEANS: false
      WRITE_ENUMS_USING_TO_STRING: true
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
      enabled: true
  session:
    store-type: none
  redis:
    database: 8
    host: localhost
    port: 6379
    timeout: 6000ms
    jedis:
      pool:
        max-active: 1000    # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10        # 连接池中的最大空闲连接
        min-idle: 5         # 连接池中的最小空闲连接
  cache:
    redis:
      cache-null-values: false
      use-key-prefix: true
      key-prefix: ${spring.application.name}
    type: redis

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL93Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
  flyway:
    baseline-version: 1 # 基线版本
    baseline-on-migrate: true # 针对非空数据库是否调用基线版本
    check-location: false # 是否开启脚本检查
    clean-on-validation-error: false # 验证错误时 是否自动清除数据库 高危操作！！！
    enabled: true
    encoding: UTF-8
    out-of-order: false # 是否允许乱序（out of order）迁移
    table: flyway_schema_version
    validate-on-migrate: true # 在运行迁移时是否要自动验证
    placeholder-replacement: false # Sets whether placeholders should be replaced.

sdcfactor:
  common:
    proxy:
    security:
      privacy-field-key: 89umtez45w7lrzlp
      password-salt: AUqLcZkYSaMv1pqN
      password-crypt-strength: 5
      jwt-token-key: G6MAKAopiJ7a8WCyb8BDgHg2xxn7872T
      jwt-token-lifetime: 720

logging:
  file: logs/${spring.application.name}.log
  level:
    root: INFO