spring:
  datasource:
    platform: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/fts?useSSL=false
    username: postgres
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      max-lifetime: 1800000
      pool-name: SDCOperationApplicationPool
      connection-timeout: 30000
      connection-test-query: select 1
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    springframework:
      security: debug
    com:
      sdc: debug
